import type { Metadata } from "next";
import "@/src/assets/css/globals.css";
import Provider from "@/components/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="w-full h-full">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
